/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#dfe3e7',
        'surface-container-high': '#e4e9ed',
        surface: '#f6fafe',
        error: '#ba1a1a',
        'on-primary-fixed': '#0f0069',
        background: '#f6fafe',
        'surface-container-low': '#f0f4f8',
        'secondary-container': '#d5e0f8',
        'primary-fixed': '#e2dfff',
        'on-surface': '#171c1f',
        'surface-container': '#eaeef2',
        'on-primary-container': '#dad7ff',
        'inverse-primary': '#c3c0ff',
        'on-tertiary-fixed': '#00201d',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary': '#ffffff',
        'inverse-surface': '#2c3134',
        'on-secondary-container': '#586377',
        'on-secondary-fixed': '#111c2d',
        outline: '#777587',
        'error-container': '#ffdad6',
        'outline-variant': '#c7c4d8',
        'on-tertiary-container': '#81eddf',
        'tertiary-fixed-dim': '#6bd8cb',
        'tertiary-container': '#006c63',
        'inverse-on-surface': '#edf1f5',
        'on-tertiary-fixed-variant': '#005049',
        'surface-container-lowest': '#ffffff',
        'on-background': '#171c1f',
        'on-surface-variant': '#464555',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f6fafe',
        'primary-container': '#4f46e5',
        'secondary-fixed': '#d8e3fb',
        'surface-tint': '#4d44e3',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#bcc7de',
        'surface-variant': '#dfe3e7',
        primary: '#3525cd',
        'surface-dim': '#d6dade',
        tertiary: '#00524b',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        secondary: '#545f73',
        'tertiary-fixed': '#89f5e7',
        'on-secondary-fixed-variant': '#3c475a',
        'on-primary-fixed-variant': '#3323cc',
      },
      fontFamily: {
        headline: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        manrope: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
