CREATE TABLE IF NOT EXISTS ResourceTags (
    TagId BIGINT NOT NULL AUTO_INCREMENT,
    TagName VARCHAR(80) NOT NULL,
    TagColor VARCHAR(30) NULL,
    Description VARCHAR(300) NULL,
    IsActive TINYINT(1) NOT NULL DEFAULT 1,
    CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UpdatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (TagId),
    CONSTRAINT UQ_resource_tags_tag_name UNIQUE (TagName)
);

CREATE INDEX IX_resource_tags_tag_name ON ResourceTags (TagName);
